version: '3.8'

services:
  dge-api-equiv:
    container_name: dge-api-equiv
    #image: devtrustcv/dge-api-sgf:0.0.0
    build: src/main/java/dge/dge_equiv_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
    networks:
      - network-postgres
volumes:

  postgres_data:

networks:
  network-postgres:
    external: true