spring.application.name=dge-equiv-api
server.servlet.context-path=/api
server.port=8087
api.version=1.0
spring.datasource.url=jdbc:postgresql://localhost:5432/db_dge_equivalencia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver



# BD secundary (db_gestao_notificacao)
spring.datasource.secondary.url=jdbc:postgresql://localhost:5432/db_igrp_dge1
spring.datasource.secondary.username=postgres
spring.datasource.secondary.password=postgres
spring.datasource.secondary.driver-class-name=org.postgresql.Driver


# BD tertiary (db_igrp_dge)
spring.datasource.tertiary.url=jdbc:postgresql://localhost:5432/db_dge_global
spring.datasource.tertiary.username=postgres
spring.datasource.tertiary.password=postgres
spring.datasource.tertiary.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.dge.dge_equiv_api.service=INFO
# BD quaternary (gestao_notificacao)
spring.datasource.quaternary.url=jdbc:postgresql://localhost:5432/gestao_notificacao
spring.datasource.quaternary.username=postgres
spring.datasource.quaternary.password=postgres
spring.datasource.quaternary.driver-class-name=org.postgresql.Driver

### FLYWAY CONFIGURATIONS
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.location=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.databaseType=postgresql

api.base.service.url=http://localhost:8083/api
api.auth.url=https://deploy.devtrust.cv/dge-api/public/token

# Credenciais
api.auth.client_id=dge-central-base
api.auth.client_secret=fOA5mn0XvyXcsnPQnJnweQOkWNOuQZwO

# Endpoints protegidos
api.acompanhamento.create=http://localhost:8088/api/process
api.validar.url=https://gateway-pdex.gov.cv/t/financas.gov/consulta_pessoa/1.0.0/getDetalhesPessoa
api.validar.token=eyJ4NXQiOiJNekUyTmpJeE9UUXdPR05tWlRFd05qa3pZbUZoT1dFMU5EVXhNREJtWkdOak1tVXdOV0kwWkRFMVlqWXhOVFkwTW1FeU1UbGhZekJtTUdFM1lqUmlNdyIsImtpZCI6Ik16RTJOakl4T1RRd09HTm1aVEV3TmprelltRmhPV0UxTkRVeE1EQm1aR05qTW1Vd05XSTBaREUxWWpZeE5UWTBNbUV5TVRsaFl6Qm1NR0UzWWpSaU13X1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJtb2JpbGlkYWRlZWxlY3RyaWNhQGRuaWNlLmdvdi5jdkBmaW5hbmNhcy5nb3YiLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IlcyRktJdVg1QTdCWTJxS2Z4eEg4WGtudExhTWEiLCJuYmYiOjE2NTg4NDQ3MjUsImF6cCI6IlcyRktJdVg1QTdCWTJxS2Z4eEg4WGtudExhTWEiLCJzY29wZSI6ImRlZmF1bHQiLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJleHAiOjIyODk5ODMyNDQsImlhdCI6MTY1ODg0NDcyNSwianRpIjoiNTBhYjkwYmMtYWM3Mi00ZGQxLWE3ZmMtMzJlM2Y5NDYxYmVkIn0.vOtZbgWTpni5qXuQDiAXsubOWjwUAy40bPackjtNWExJ_6n2s5hFB040T0VWymy5G6iuUYgGLOLFjPcQvIl8fB6rl73pg5sAvUncbyfBG1bXpoBCbgu7O19Wq0ZZhmqQ3APHU5LAZZrL4CSgesBMX0GlVX56mzALE7slyU0TJ_OTrdHcpOeWvV9_Ooan3YhWG4bMRDRK-2yeSK_K_R6_k8CkFkKuA6HPwMTZZVXtDx8F3kiZcUiNaAGRJjj-3azSSQkpxF9_9ZWOfz9cJu1ZS8KZZJ0Ot7zlMD0Qxz5BrXVpz3-WgHXISR9mXqnvSimbnyEy-_i3JxTFeD-965p4Gw
api.acompanhamento.update=http://localhost:8088/api/process/update
reporter.eqv.url=https://deploy.devtrust.cv/report-dge/
process.equiv-url=http://localhost:8080/dge/api/process/global
process.equiv-profile-code=admin.equiv
process.equiv-email=demo@nosi.cv
api.base.service.Duc=https://mock.apidog.com/m1/1156350-1149291-default/duc/gerar
link.report.integration.sigof.duc=https://portalrep.gov.cv/reports/rwservlet?SIGOF_DUC&p_nu_duc=
link.mf.duc=https://www.mf.gov.cv/web/mf/pagamento-duc?entidade=
link.api.duc.check=http://localhost:8080/dge/services/feedback/pagamento?duc=
api.pessoa.url=http://62.84.179.137:8080/api-global/pessoa
process.equiv-reclamacao=http://localhost:8080/dge/services/portal/reclamacao
doc.open=http://localhost:8080/dge/app/webapps?r=global_dge/Document_viewer/index&dad=global_dge&target=_blank&isPublic=1&lang=pt_PT
