version: '3.8'

services:
  dge-api-sgf:
    container_name: dge-api-sgf
    #image: devtrustcv/dge-api-sgf:0.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
    volumes:
      - ./src/main/resources/application.properties:/app/config/application.properties
      - ./src/main/resources/db/migration/:/app/flyway/sql/  # Montando os scripts do Flyway
    networks:
      - network-postgres
volumes:
  postgres_data:

networks:
  network-postgres:
    external: true